Error handling fixed
Code-the-Dream-School/hh-team4-back pull request #15
Opened 2024-11-21 22:03 UTC by up2code3

## Description

_1) What does this PR do? 2) List out what you did._

## Related Issue

_Provide a link to the related issue 

## Type of Changes

_Feature update/change/addition, bug fix, styling update, etc._

## Acceptance Criteria

_Include the checked-off acceptance criteria from the issue._

## Update Screenshots

_Provide screenshots of the view before and after the changes._

### Before

### After

## Testing Instructions

_In a list format, tell us how to test this PR._

## Learnings (Optional)

_Document any things you learned or 'gotchas' you experienced._

2024-11-22 00:40 UTC, GinaCastromonte requested changes

2024-11-22 00:40 UTC, GinaCastromonte commented on src/errors/notFound.js
> +    this.StatusCode = StatusCodes.NOT_FOUND;
did you mean this.statusCode?

2024-11-22 00:40 UTC, GinaCastromonte commented on src/errors/forbidden.js
> +    this.StatusCode = StatusCodes.FORBIDDEN;
did you mean this.statusCode?

2024-11-22 00:50 UTC, up2code3 commented on src/errors/notFound.js
> +    this.StatusCode = StatusCodes.NOT_FOUND;
YUP! Vanessa was saying, I got this weird StatusCode error as I was reading your comment. its fixed in the most recent commit.

2024-11-22 00:50 UTC, up2code3 commented on src/errors/forbidden.js
> +    this.StatusCode = StatusCodes.FORBIDDEN;
fixed

2024-11-22 00:53 UTC, GinaCastromonte approved these changes
Awesome!

2024-11-23 01:05 UTC, vsrodriguez3 approved these changes

2024-11-23 16:21 UTC, merged